version: '3'
services:
  app:
    build:
      context: .
    tty: true
    env_file:
      - .env
    #command: bundle exec puma -C config/puma.rb
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log

#  db:
#    #mage: mysql:8.0
#    environment:
#      - MYSQL_DATABASE=rails_db
#      - MYSQL_USER=rails_user
#      - MYSQL_PASSWORD=rails_password
#      - MYSQL_ROOT_PASSWORD=secret
#      - TZ=Asia/Tokyo
#    volumes:
#      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - 80:80

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
